const data = [
    {
        "lat": 13.621775,
        "lng": 123.194824,
        "projectName": "Improving Crop Insurance in the Philippines",
        "country": "Philippines",
        "location": "Naga City (On-site)",
        "startDate": "Aug 2010",
        "completionDate": "Jun 2012",
        "partner": "On-site",
        "client": "Innovations for Poverty Actions - Philippines",
        "clientType": "Non-Profit",
        "description": "Worked as Project Associate and GIS expert. The 2-year project aimed to understand the perception of farmers towards crop insurance, its percieved benefits, and  shortcomings. Results of the study was used to develop policies on how crop insurance service can be improved as well as to educate, encourage and inform farmers on the importance of crop insurance.",
        "projectValue": "",
        "projectScale": "",
        "status": "Project",
        "sector1": "Agriculture",
        "sector2": "Spatial Analysis",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 14.5869,
        "lng": 121.0614,
        "projectName": "",
        "country": "Philippines",
        "location": "Pasig City (On-site)",
        "startDate": "Aug 2012",
        "completionDate": "Apr 2017",
        "partner": "On-site",
        "client": "Geodata Systems Technologies Inc.",
        "clientType": "Private",
        "description": "Worked as Esri ArGIS Trainer and conducted GIS classes, from basic to advance classes.",
        "projectValue": "",
        "projectScale": "",
        "status": "Full-time",
        "sector1": "GIS Capacity Building",
        "sector2": "GIS Capacity Building",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 14.5353447221241,
        "lng": 121.040937540792,
        "projectName": "Enhancement of Topographic Map Production System with ArcGIS\n(Phase1 and 2)",
        "country": "Philippines",
        "location": "Taguig City (On-site)",
        "startDate": "Feb 2014",
        "completionDate": "Dec 2016",
        "partner": "On-site",
        "client": "NationalMapping and ResourceInformationAuthority (NAMRIA)",
        "clientType": "Government",
        "description": "Worked as a GIS Specialist/trainer. Upgrade current ArcGIS Systems, configured ArcGIS Workflow Manager, ArcGIS Production Mapping, and conduct technical workshops for efficient topographic map updating and production.",
        "projectValue": "",
        "projectScale": "",
        "status": "Project",
        "sector1": "Web GIS App Development",
        "sector2": "GIS Capacity Building",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 34.0572744580545,
        "lng": -117.194918802316,
        "projectName": "",
        "country": "USA",
        "location": "Redlands, Calirfornia (On-site)",
        "startDate": "Apr2014 ",
        "completionDate": "Jun 2014",
        "partner": "On-site",
        "client": "Esri Inc.",
        "clientType": "Private",
        "description": "Interned at Esri's Headquarters in Redlands, California to learn about the ArcGIS WorkFlow Manager and Production Mapping extensions. This is to support technology upgrade, knowledge transfer, and build the capacity of NAMRIA to expedite the updating of 1:10,000 and 1:50,000 topographic maps.",
        "projectValue": "",
        "projectScale": "",
        "status": "Project",
        "sector1": "GIS Capacity Building",
        "sector2": "GIS Capacity Building",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 14.6557169338992,
        "lng": 121.07540788493,
        "projectName": "GIS Capacity Building for Metropolitan Waterworks and Sewerage System",
        "country": "Philippines",
        "location": "Quezon City (On-site)",
        "startDate": "Sep 2016",
        "completionDate": "Mar 2017",
        "partner": "On-site",
        "client": "Metropolitan Waterworksand Sewerage System (MWSS)",
        "clientType": "Government",
        "description": "Technical Lead (GIS). The objective of the project was building up the GIS capacity of MWSS to be able to utilize data and reports coming from the two biggest water concessionaires in Metro Manila.",
        "projectValue": "",
        "projectScale": "",
        "status": "Project",
        "sector1": "Water Utilities",
        "sector2": "GIS Capacity Building",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 14.6519782546083,
        "lng": 121.058604958465,
        "projectName": "Enhancing PHIVOLCS’s Geospatial Systemswith the ArcGIS Platform",
        "country": "Philippines",
        "location": "Quezon City (On-site)",
        "startDate": "Aug 2017",
        "completionDate": "Sep 2018",
        "partner": "On-site",
        "client": "Philippine Institute of Volcanology and Seismology (PHIVOLCS)",
        "clientType": "Government",
        "description": "Technical Lead (GIS). The objective of the project was the development of Web-based GIS Disaster Management applications using COTS ArcGIS Platform.",
        "projectValue": "",
        "projectScale": "",
        "status": "Project",
        "sector1": "Disaster Risk Management",
        "sector2": "Web GIS App Development",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 21.060838109344,
        "lng": 105.819519103303,
        "projectName": "-",
        "country": "Vietnam",
        "location": "Hanoi City (On-site)",
        "startDate": "Aug 2017",
        "completionDate": "Aug 2021",
        "partner": "On-site",
        "client": "",
        "clientType": "Private",
        "description": "Worked as geospatial expert and deputy manager for an urban and regional planning firm.",
        "projectValue": "",
        "projectScale": "",
        "status": "Full-time",
        "sector1": "Urban and Regional Planning",
        "sector2": "Spatial Analysis",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 22.3312820635813,
        "lng": 78.2694877250042,
        "projectName": "Web-based GIS Sewage Treatment Plants Information System",
        "country": "India",
        "location": "",
        "startDate": "Nov 2017",
        "completionDate": "Mar 2018",
        "partner": "Remote",
        "client": "Client: Sunjay Gupta and Associates",
        "clientType": "Private",
        "description": "The Web GIS applications were developed to serve as a visual, interactive web-based medium in viewing critical information about sewerage treatment plants spread throughout India. The GIS web map not only shows the location and attribute of the sewerage treatment plants, but also several filters, and analysis tools were also embedded to help decision-makers understand their data, providing meaningful insights and informed decision making.",
        "projectValue": "",
        "projectScale": "",
        "status": "Project",
        "sector1": "Water Utilities",
        "sector2": "Web GIS App Development",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 16.8077325045983,
        "lng": 107.09622774753,
        "projectName": "Preparation of Dong Ha City Urban Master Plan, Quang Tri Province",
        "country": "Vietnam",
        "location": "Dong Ha City (Remote)",
        "startDate": "Nov 2017",
        "completionDate": "Oct 2018",
        "partner": "On-site",
        "client": "Nippon Koei Vietnam",
        "clientType": "Private",
        "description": "Worked as a GIS expert. Dong Ha is reviewing and upgrading its Urban Development Plan to respond to the changing economic opportunities provided by the East-West highway that connects Vietnam to Laos, Thailand, and Myanmar. The city master plan upgrade also responds to the opportunity for Dong Ha city to accelerate the economic growth of Quang Tri Province drawing upon its GMS corridor town\nstatus.",
        "projectValue": "",
        "projectScale": "",
        "status": "Project",
        "sector1": "Urban and Regional Planning",
        "sector2": "Information Technology",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 10.8314255705428,
        "lng": 106.761940381743,
        "projectName": "GIS Technology Based Technical Management For Power Transmission Grid",
        "country": "Vietnam",
        "location": "Ho Chi Minh City, Hanoi City (On-site)",
        "startDate": "Nov 2018",
        "completionDate": "Aug 2021",
        "partner": "On-site",
        "client": "Vietnam Electricity National Power Transmission (EVN NPT)",
        "clientType": "Government",
        "description": "During my tenure, I worked as a project coordinator and GIS expert. EVN NPT’s objective was to deploy an Enterprise-GIS system for managing and operating the transmission grid. Additionally, the project aimed to facilitate the planning, construction, and operation of smart transmission infrastructure in the context of Industry 4.0. The project provided essential guidance for implementing “GIS technology-based technical management for the power transmission grid” within the National Power Transmission Corporation.",
        "projectValue": "",
        "projectScale": "",
        "status": "Project",
        "sector1": "Energy",
        "sector2": "Information Technology",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 43.6539875592704,
        "lng": -70.272139497885,
        "projectName": "Pulse Analytics- GIS based Marketing Segments Application",
        "country": "USA",
        "location": "United States (Remote)",
        "startDate": "Aug 2019",
        "completionDate": "Apr 2020",
        "partner": "Remote",
        "client": "Coria Inc.",
        "clientType": "Private",
        "description": "In this project, my role as a GIS expert was pivotal. Our goal was to develop an app that empowers marketing teams, product distributors, and service providers to gain insights into US market segments. Here’s how we achieved it:\n\nData Integration: We seamlessly combined updated census block data, including factors like age, education, and income, with social media-derived information.\nSegment Visualization: Using this integrated data, we created visualizations to highlight areas in the US with high concentrations of specific market segments. These segments included dog owners, wine enthusiasts, coffee lovers, and high-income millennials.\nStrategic Placement: Armed with these insights, companies could strategically position their products and services in the most relevant regions, optimizing their reach and impact.\nOur app bridged the gap between data and decision-making, enabling businesses to make informed choices about where to focus their efforts.",
        "projectValue": "",
        "projectScale": "",
        "status": "Project",
        "sector1": "Marketting",
        "sector2": "Web GIS App Development",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 21.0303380071392,
        "lng": 105.761677901449,
        "projectName": "Capacity building of GreenID Vietnam towards utilization of GIS in Renewable Energy\r\nProjects",
        "country": "Vietnam",
        "location": "Hanoi City (On-site)",
        "startDate": "Oct 2020",
        "completionDate": "Feb 2021",
        "partner": "On-site",
        "client": "GreenID Vietnam",
        "clientType": "Non-Profit",
        "description": "The engagement with GreenID aims to build up the capacity of the organization in applying GIS in their renewable energy projects such as solar rooftop installation, study on Agrovoltaics, and reducing carbon emissions. The objective is to build the capacity to develop in-house GIS specialists for sustainable organizational growth.",
        "projectValue": "",
        "projectScale": "",
        "status": "Project",
        "sector1": "Renewable Energy",
        "sector2": "GIS Capacity Building",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 14.5875588741723,
        "lng": 121.058750414979,
        "projectName": "TA-9414: Supporting AdaptationDecision Making for Climate Resilient\nInvestments",
        "country": "Philippines",
        "location": "City of Manila (Remote)",
        "startDate": "Jun 2020",
        "completionDate": "May 2021",
        "partner": "Remote",
        "client": "Asian Development Bank",
        "clientType": "ODA",
        "description": "The knowledge and support TA is expected to deliver three key outputs: (i) develop country-specific climate projections to support planning; (ii) provide technical support for ADB operations to integrate climate resilience features; and (iii) good practice guidance on climate-resilient infrastructure design and associated training modules developed and delivered. I was responsible for the compilation, management, and development of the datasets generated for the adaptation guidance document into a user- friendly and searchable format.",
        "projectValue": "",
        "projectScale": "",
        "status": "Project",
        "sector1": "Climate Resilience",
        "sector2": "Database Management",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 14.7450011389292,
        "lng": -86.7344308848235,
        "projectName": "Enhancing the Terra-i Project",
        "country": "Honduras",
        "location": "",
        "startDate": "Oct 2021",
        "completionDate": "Feb 2022",
        "partner": "Remote",
        "client": "The International Center for Tropical Agriculture (CIAT)",
        "clientType": "Non-Profit",
        "description": "About: Terra-i detects land-cover changes resulting from human activities in near real-time, producing updates every 16 days. Currently it works for the whole of Latin America and the tropics. Terra-i is a collaboration between the International Center for Tropical Agriculture (CIAT - DAPA, based in Colombia), The program on Forestry, Trees and Agroforestry (FTA) ,The Nature Conservancy (TNC, global environmental organization), the School of Business and Engineering (HEIG-VD, based in Switzerland) and King’s College London (KCL, based in the UK).\n\nThe system is based on the premise that natural vegetation follows a predictable pattern of changes in greenness from one date to the next brought about by site- specific land and climatic conditions over the same period. A so-called computational neural network is ‘trained’ to understand the normal pattern of changes in vegetation greenness in relation to terrain and rainfall for a site and then marks areas as changed where the greenness suddenly changes well beyond these normal limits. Running on many computers this analysis is refreshed with new imagery every 16 days and for every 250m square of land. The specific engagement with CIAT focuses on coffee driven deforestation and existing coffee farms risks.",
        "projectValue": "",
        "projectScale": "",
        "status": "Project",
        "sector1": "Agriculture",
        "sector2": "Sustianbility",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 10.5143550975052,
        "lng": 105.169486964666,
        "projectName": "Web GIS Dashboard Development to map the Solar Panels installation activities in An\nGiang, Dak Lak, and Tra Vinh Province, Vietnam",
        "country": "Vietnam",
        "location": "An Giang Province, Dak Lak Province, Tra Vinh Province (Remote)",
        "startDate": "Dec 2021",
        "completionDate": "rch 2022",
        "partner": "Remote",
        "client": "GreenID Vietnam",
        "clientType": "Non-Profit",
        "description": "Worked as GIS expert. GreenID Vietnam is a non-profit organization which promotes sustainable and renewable energy acceptance and acceleration in Vietnam. Thru its partners, they are installing rooftop solar panels to provide green and sustainable electricity for off-grid ethnic communities. Mr. Losaria was hired as a GIS project consultant for mapping and developing a web-based GIS dashboard for the solar panels installed by GreenID partners in An Giang, Dak Lak, and Tra Vinh provinces to provide electricity to off-grid ethnic minorities. The platform used is Esri ArcGIS.",
        "projectValue": "",
        "projectScale": "",
        "status": "Project",
        "sector1": "Renewable Energy",
        "sector2": "Information Technology",
        "photo1": "https://assets-global.website-files.com/6213793139128577f6ba751b/62eb8f0aae610ffe325ea1a8_green_id_dashboard.webp",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 14.5559176172652,
        "lng": 121.021127212699,
        "projectName": "The Collaborating, Learning and Adapting for Improved Development (CLAimDev) -\r\nUSAID",
        "country": "Philippines",
        "location": "City of Manila (Remote)",
        "startDate": "Dec 2021",
        "completionDate": "May 2022",
        "partner": "Remote",
        "client": "Panagora Group, USAID",
        "clientType": "Non-Profit",
        "description": "Worked as GIS expert and cartographer. The Collaborating, Learning, and Adapting for Improved Development (CLAimDev) activity’s purpose is to bolster the capacity of USAID/Philippines to effectively lead and practice collaborating, learning, and adapting (CLA), which has the broader goal of enhancing USAID’s development effectiveness. The CLAimDev activity will strengthen the evidence base of USAID/Philippines by implementing select monitoring, evaluation, research, and other analytical tasks to inform key strategic decisions.",
        "projectValue": "",
        "projectScale": "",
        "status": "Project",
        "sector1": "Cartography",
        "sector2": "Development",
        "photo1": "https://assets-global.website-files.com/6213793139128577f6ba751b/6218300ee8b7708391e7e9c9_Dinagat.png",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 54.6099955714273,
        "lng": -2.42230813255042,
        "projectName": "-",
        "country": "United Kingdom",
        "location": "",
        "startDate": "",
        "completionDate": "",
        "partner": "Remote",
        "client": "Searchland UK",
        "clientType": "Private",
        "description": "Short term project. Worked as GIS Expert for Searchland UK, a leading real estate platform based in the UK.",
        "projectValue": "",
        "projectScale": "",
        "status": "Project",
        "sector1": "Real Estate",
        "sector2": "GIS Data Extraction",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": -31.0102936382499,
        "lng": 150.403109274337,
        "projectName": "-",
        "country": "Australia",
        "location": "",
        "startDate": "",
        "completionDate": "",
        "partner": "Remote",
        "client": "Individual Client",
        "clientType": "Private",
        "description": "Hired as GIS expert to produce Net Plantable Area Maps for several properties in Australia.",
        "projectValue": "",
        "projectScale": "",
        "status": "Project",
        "sector1": "Real Estate",
        "sector2": "GIS Data Extraction",
        "photo1": "https://assets-global.website-files.com/6213793139128577f6ba751b/62ea6ceb0175673ed95b4b45_Layout1-p-800.jpg",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 40.0023425861252,
        "lng": -83.0049312297663,
        "projectName": "-",
        "country": "USA",
        "location": "Ohio (Remote)",
        "startDate": "",
        "completionDate": "",
        "partner": "Remote",
        "client": "",
        "clientType": "Private",
        "description": "-",
        "projectValue": "",
        "projectScale": "",
        "status": "Project",
        "sector1": "GIS Data Extraction",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 24.2455416806188,
        "lng": 44.2660540632862,
        "projectName": "-",
        "country": "Saudi Arabia",
        "location": "",
        "startDate": "",
        "completionDate": "",
        "partner": "Remote",
        "client": "Individual Client",
        "clientType": "Private",
        "description": "Contracted as a GIS expert to perform least cost path analysis to delinieate all possible ancient trade routes used in the middle east back in the day.",
        "projectValue": "",
        "projectScale": "",
        "status": "Project",
        "sector1": "Archeaology",
        "sector2": "Spatial Analysis",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 10.7810454269881,
        "lng": 106.698425766226,
        "projectName": "-",
        "country": "Vietnam",
        "location": "Ho Chi Minh City (On-site)",
        "startDate": "Aug 2022",
        "completionDate": "Till date",
        "partner": "On-site",
        "client": "enCity",
        "clientType": "Private",
        "description": "Senior GIS associate supporting varying projects. Geospatial data acqusition, analysis and visualization. Web map app development.",
        "projectValue": "",
        "projectScale": "",
        "status": "Full-time",
        "sector1": "Urban and Regional Planning",
        "sector2": "GIS Web App Development",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 10.8203192,
        "lng": 106.7074485,
        "projectName": "Thu Duc City web GIS Platform for planning and stakeholder engagement",
        "country": "Vietnam",
        "location": "Thu Duc City (Remote)",
        "startDate": "Nov 2022",
        "completionDate": "Nov 2022",
        "partner": "On-site",
        "client": "Thu Duc City",
        "clientType": "Private",
        "description": "Technical Lead (GIS). In close coordination with Thủ Đức City’s Urban Management Division, enCity has developed an interactive online dashboard to enable the city’s planners in better decision-making through side-by-side comparison of various spatial information (existing conditions, the existing land use plan and the revised land use plan).",
        "projectValue": "",
        "projectScale": "",
        "status": "Project",
        "sector1": "GIS Web App Development",
        "sector2": "Urban and Regional Planning",
        "photo1": "https://raw.githubusercontent.com/cmlosariaGIS/enCityProjects/main/Projects/01_Thu%20Duc%20City%20GIS%20Planning%20Platform/Images/Picture1.jpg",
        "photo2": "https://raw.githubusercontent.com/cmlosariaGIS/enCityProjects/main/Projects/01_Thu%20Duc%20City%20GIS%20Planning%20Platform/Images/Picture2.JPG",
        "attachment": ""
    },
    {
        "lat": 21.0055645786822,
        "lng": 105.803904253652,
        "projectName": "-",
        "country": "Vietnam",
        "location": "Hanoi City",
        "startDate": "Jan 2023",
        "completionDate": "Till date",
        "partner": "On-site",
        "client": "enCity / enSigthful / enFarm Agritech",
        "clientType": "Private",
        "description": "Senior GIS associate supporting varying projects. Geospatial data acqusition, analysis and visualization. Web map app development.",
        "projectValue": "",
        "projectScale": "",
        "status": "Full-time",
        "sector1": "Agriculture",
        "sector2": "GIS Web App Development",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    }
];

// Add more Project data rows as needed