const data = [
    {
        "lat": 13.621775,
        "lng": 123.194824,
        "projectName": "Improving Crop Insurance in the Philippines",
        "country": "Philippines",
        "location": "Naga City ",
        "startDate": "Aug 2010",
        "completionDate": "Jun 2012",
        "partner": "On-site",
        "client": "Innovations for Poverty Actions - Philippines",
        "clientType": "Non-profit Organizations",
        "description": "Worked as Project Associate and GIS expert. The 2-year project aimed to understand the perception of farmers towards crop insurance, its percieved benefits, and  shortcomings. Results of the study was used to develop policies on how crop insurance service can be improved as well as to educate, encourage and inform farmers on the importance of crop insurance.",
        "projectValue": "",
        "projectScale": "",
        "status": "Project-based",
        "sector1": "Spatial Analysis",
        "sector2": "Agriculture",
        "photo1": "https://images.pexels.com/photos/164504/pexels-photo-164504.jpeg",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 14.5869,
        "lng": 121.0614,
        "projectName": "Senior GIS Specialist (Instructor)",
        "country": "Philippines",
        "location": "Pasig City ",
        "startDate": "Aug 2012",
        "completionDate": "Apr 2017",
        "partner": "On-site",
        "client": "Geodata Systems Technologies Inc.",
        "clientType": "Private",
        "description": "Worked as Esri ArGIS Trainer and conducted GIS classes, from basic to advance GIS classes. Implemented several GIS projects with clients in the utilities and DRM sector",
        "projectValue": "",
        "projectScale": "",
        "status": "Full-time",
        "sector1": "GIS Capacity Building",
        "sector2": "Spatial Analysis",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 14.5353447221241,
        "lng": 121.040937540792,
        "projectName": "Enhancement of Topographic Map Production System with ArcGIS\n(Phase1 and 2)",
        "country": "Philippines",
        "location": "Taguig City ",
        "startDate": "Feb 2014",
        "completionDate": "Dec 2016",
        "partner": "On-site",
        "client": "National Mapping and Resource InformationAuthority (NAMRIA)",
        "clientType": "Government",
        "description": "Worked as a GIS Specialist and trainer. Upgrade current ArcGIS Systems, configured ArcGIS Workflow Manager, ArcGIS Production Mapping, and conduct technical workshops for efficient topographic map updating and production.",
        "projectValue": "",
        "projectScale": "",
        "status": "Project-based",
        "sector1": "Web GIS App Development",
        "sector2": "GIS Capacity Building",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 34.0572744580545,
        "lng": -117.194918802316,
        "projectName": "Esri Internship",
        "country": "USA",
        "location": "Redlands, Calirfornia ",
        "startDate": "Apr 2014",
        "completionDate": "Jun 2014",
        "partner": "On-site",
        "client": "Esri Inc.",
        "clientType": "Private",
        "description": "Interned at Esri's Headquarters in Redlands, California to learn about the ArcGIS WorkFlow Manager and Production Mapping extensions. This is to support technology upgrade, knowledge transfer, and build the capacity of NAMRIA to expedite the updating of 1:10,000 and 1:50,000 topographic maps.",
        "projectValue": "",
        "projectScale": "",
        "status": "Project-based",
        "sector1": "GIS Capacity Building",
        "sector2": "Cartography",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 14.6557169338992,
        "lng": 121.07540788493,
        "projectName": "GIS Capacity Building for Metropolitan Waterworks and Sewerage System",
        "country": "Philippines",
        "location": "Quezon City ",
        "startDate": "Sep 2016",
        "completionDate": "Mar 2017",
        "partner": "On-site",
        "client": "Metropolitan Waterworks and Sewerage System (MWSS)",
        "clientType": "Government",
        "description": "Technical Lead (GIS). The objective of the project was building up the GIS capacity of MWSS to be able to utilize data and reports coming from the two biggest water concessionaires in Metro Manila, Maynilad and Manila Waters.",
        "projectValue": "",
        "projectScale": "",
        "status": "Project-based",
        "sector1": "GIS Capacity Building",
        "sector2": "Wastewater Utilities",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 14.6519782546083,
        "lng": 121.058604958465,
        "projectName": "Enhancing PHIVOLCS Geospatial Systemswith the ArcGIS Platform",
        "country": "Philippines",
        "location": "Quezon City ",
        "startDate": "Aug 2017",
        "completionDate": "Sep 2018",
        "partner": "On-site",
        "client": "Philippine Institute of Volcanology and Seismology (PHIVOLCS)",
        "clientType": "Government",
        "description": "Technical Lead (GIS). The objective of the project was the development of Web-based GIS Disaster Management applications using COTS ArcGIS Platform.",
        "projectValue": "",
        "projectScale": "",
        "status": "Project-based",
        "sector1": "Web GIS App Development",
        "sector2": "Disaster Risk Management",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 21.060838109344,
        "lng": 105.819519103303,
        "projectName": "Geospatial Expert, Deputy Manager",
        "country": "Vietnam",
        "location": "Hanoi City ",
        "startDate": "Aug 2017",
        "completionDate": "Aug 2021",
        "partner": "On-site",
        "client": "Spatial Decisions Vietnam",
        "clientType": "Private",
        "description": "I worked as geospatial expert and deputy manager for an urban and regional planning firm. Responsibilities included Proof of Concept app development, business development, networking and office management.",
        "projectValue": "",
        "projectScale": "",
        "status": "Full-time",
        "sector1": "Spatial Analysis",
        "sector2": "Urban and Regional Planning",
        "photo1": "https://i.ibb.co/b2WvNPn/Capture4.jpg",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 22.3312820635813,
        "lng": 78.2694877250042,
        "projectName": "Web-based GIS Sewage Treatment Plants Information System",
        "country": "India",
        "location": "",
        "startDate": "Nov 2017",
        "completionDate": "Mar 2018",
        "partner": "Remote",
        "client": "Sunjay Gupta and Associates",
        "clientType": "Private",
        "description": "Built Web GIS applications to serve as a visual, interactive web-based medium in viewing critical information about sewerage treatment plants spread throughout India. The GIS web map not only shows the location and attribute of the sewerage treatment plants, but also several filters, and analysis tools were also embedded to help decision-makers understand their data, providing meaningful insights and informed decision making.",
        "projectValue": "",
        "projectScale": "",
        "status": "Project-based",
        "sector1": "Web GIS App Development",
        "sector2": "Wastewater Utilities",
        "photo1": "https://i.ibb.co/99yRsgK/Capture3.jpg",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 16.8077325045983,
        "lng": 107.09622774753,
        "projectName": "Preparation of Dong Ha City Urban Master Plan, Quang Tri Province",
        "country": "Vietnam",
        "location": "Dong Ha City ",
        "startDate": "Nov 2017",
        "completionDate": "Oct 2018",
        "partner": "On-site",
        "client": "Nippon Koei Vietnam",
        "clientType": "Private",
        "description": "Worked as a GIS expert. Dong Ha is reviewing and upgrading its Urban Development Plan to respond to the changing economic opportunities provided by the East-West highway that connects Vietnam to Laos, Thailand, and Myanmar. The city master plan upgrade also responds to the opportunity for Dong Ha city to accelerate the economic growth of Quang Tri Province drawing upon its GMS corridor town status.",
        "projectValue": "",
        "projectScale": "",
        "status": "Project-based",
        "sector1": "Spatial Analysis",
        "sector2": "Urban and Regional Planning",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 10.8314255705428,
        "lng": 106.761940381743,
        "projectName": "GIS Technology Based Technical Management For Power Transmission Grid",
        "country": "Vietnam",
        "location": "Ho Chi Minh City, Hanoi City ",
        "startDate": "Nov 2018",
        "completionDate": "Aug 2021",
        "partner": "On-site",
        "client": "Vietnam Electricity National Power Transmission (EVN NPT)",
        "clientType": "Government",
        "description": "I worked as a project coordinator and GIS expert. EVN NPT’s objective was to deploy an Enterprise-GIS system for managing and operating the transmission grid. Additionally, the project aimed to facilitate the planning, construction, and operation of smart transmission infrastructure in the context of Industry 4.0. The project provided essential guidance for implementing a “GIS technology-based technical management for the power transmission grid” within the National Power Transmission Corporation.",
        "projectValue": "",
        "projectScale": "",
        "status": "Project-based",
        "sector1": "Electric Transmission",
        "sector2": "Information Technology",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 43.6539875592704,
        "lng": -70.272139497885,
        "projectName": "Pulse Analytics - GIS based Marketing Segments Application",
        "country": "USA",
        "location": "United States ",
        "startDate": "Aug 2019",
        "completionDate": "Apr 2020",
        "partner": "Remote",
        "client": "Coria Inc.",
        "clientType": "Private",
        "description": "I was hired as a GIS expert to help develop an app that empowers marketing teams, product distributors, and service providers to gain insights into US market demographic segments. Our app bridged the gap between data and decision-making, enabling businesses to make informed choices about where to focus their services based on the demographic profile.",
        "projectValue": "",
        "projectScale": "",
        "status": "Project-based",
        "sector1": "Web GIS App Development",
        "sector2": "Marketting",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 21.0303380071392,
        "lng": 105.761677901449,
        "projectName": "Capacity building of GreenID Vietnam towards utilization of GIS in Renewable Energy\r\nProjects",
        "country": "Vietnam",
        "location": "Hanoi City ",
        "startDate": "Oct 2020",
        "completionDate": "Feb 2021",
        "partner": "On-site",
        "client": "GreenID Vietnam",
        "clientType": "Non-profit Organizations",
        "description": "The engagement with GreenID aims to build up the capacity of the organization in applying GIS in their renewable energy projects such as solar rooftop installation, study on Agrovoltaics, and reducing carbon emissions. The objective is to build the capacity to develop in-house GIS specialists for sustainable organizational growth.",
        "projectValue": "",
        "projectScale": "",
        "status": "Project-based",
        "sector1": "Renewable Energy",
        "sector2": "GIS Capacity Building",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 14.5875588741723,
        "lng": 121.058750414979,
        "projectName": "TA-9414: Supporting AdaptationDecision Making for Climate Resilient\nInvestments",
        "country": "Philippines",
        "location": "City of Manila ",
        "startDate": "Jun 2020",
        "completionDate": "May 2021",
        "partner": "Remote",
        "client": "Asian Development Bank",
        "clientType": "ODAs, Financial Institutions",
        "description": "Hired as a database management specialist working with Excel, VBA Macro. The knowledge and support TA is expected to deliver three key outputs: (i) develop country-specific climate projections to support planning; (ii) provide technical support for ADB operations to integrate climate resilience features; and (iii) good practice guidance on climate-resilient infrastructure design and associated training modules developed and delivered. I was responsible for the compilation, management, and development of the datasets generated for the adaptation guidance document into a user- friendly and searchable format.",
        "projectValue": "",
        "projectScale": "",
        "status": "Project-based",
        "sector1": "Database Management",
        "sector2": "Climate Resilience",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 14.7450011389292,
        "lng": -86.7344308848235,
        "projectName": "Enhancing the Terra-i Project",
        "country": "Honduras",
        "location": "",
        "startDate": "Oct 2021",
        "completionDate": "Feb 2022",
        "partner": "Remote",
        "client": "The International Center for Tropical Agriculture (CIAT)",
        "clientType": "Non-profit Organizations",
        "description": "Hired as a GIS consultant with specific focus on developing customized spatial analysis tools and web map application using the ArcGIS platform. The main purpose is for coffee organizations determine if their coffee beans are being sourced from coffe induced deforasted areas.",
        "projectValue": "",
        "projectScale": "",
        "status": "Project-based",
        "sector1": "GIS Web App Development",
        "sector2": "Agriculture",
        "photo1": "https://i.ibb.co/rxfKqL0/terra-i.png",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 10.5143550975052,
        "lng": 105.169486964666,
        "projectName": "Web GIS Dashboard Development to map the Solar Panels installation activities in An\nGiang, Dak Lak, and Tra Vinh Province, Vietnam",
        "country": "Vietnam",
        "location": "An Giang Province, Dak Lak Province, Tra Vinh Province ",
        "startDate": "Dec 2021",
        "completionDate": "Mar 2022",
        "partner": "Remote",
        "client": "GreenID Vietnam",
        "clientType": "Non-profit Organizations",
        "description": "Hired as GIS expert. GreenID Vietnam is a Non-profit Organizations organization which promotes sustainable and renewable energy acceptance and acceleration in Vietnam. Thru its partners, they are installing rooftop solar panels to provide green and sustainable electricity for off-grid ethnic communities. I was hired as a GIS project consultant for mapping and developing a web-based GIS dashboard for the solar panels installed by GreenID partners in An Giang, Dak Lak, and Tra Vinh provinces to provide electricity to off-grid ethnic minorities.",
        "projectValue": "",
        "projectScale": "",
        "status": "Project-based",
        "sector1": "Renewable Energy",
        "sector2": "GIS Web App Development",
        "photo1": "https://assets-global.website-files.com/6213793139128577f6ba751b/62eb8f0aae610ffe325ea1a8_green_id_dashboard.webp",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 14.5559176172652,
        "lng": 121.021127212699,
        "projectName": "The Collaborating, Learning and Adapting for Improved Development (CLAimDev) -\r\nUSAID",
        "country": "Philippines",
        "location": "City of Manila ",
        "startDate": "Dec 2021",
        "completionDate": "May 2022",
        "partner": "Remote",
        "client": "Panagora Group, USAID",
        "clientType": "Non-profit Organizations",
        "description": "Worked as GIS expert and cartographer. The Collaborating, Learning, and Adapting for Improved Development (CLAimDev) activity’s purpose is to bolster the capacity of USAID/Philippines to effectively lead and practice collaborating, learning, and adapting (CLA), which has the broader goal of enhancing USAID’s development effectiveness. The CLAimDev activity will strengthen the evidence base of USAID/Philippines by implementing select monitoring, evaluation, research, and other analytical tasks to inform key strategic decisions.",
        "projectValue": "",
        "projectScale": "",
        "status": "Project-based",
        "sector1": "Cartography",
        "sector2": "Development",
        "photo1": "https://assets-global.website-files.com/6213793139128577f6ba751b/6218300ee8b7708391e7e9c9_Dinagat.png",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 54.6099955714273,
        "lng": -2.42230813255042,
        "projectName": "GIS Specialist",
        "country": "United Kingdom",
        "location": "",
        "startDate": "Jan 2022",
        "completionDate": "Mar 2022",
        "partner": "Remote",
        "client": "Searchland UK",
        "clientType": "Private",
        "description": "Short term project. Worked as GIS Expert for Searchland UK, a leading real estate platform based in the UK. Specific role was digitized real estate parcels using SHLAA as guide",
        "projectValue": "",
        "projectScale": "",
        "status": "Project-based",
        "sector1": "Spatial Data Extraction",
        "sector2": "Real Estate",
        "photo1": "https://assets-global.website-files.com/63ea676ef623201282c8f642/65772ec3bc2e223dc66b4361_Land_and_new_homes-p-800.webp",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": -31.0102936382499,
        "lng": 150.403109274337,
        "projectName": "GIS Specialist",
        "country": "Australia",
        "location": "",
        "startDate": "Jan 2022",
        "completionDate": "Mar 2022",
        "partner": "Remote",
        "client": "Individual client",
        "clientType": "Private",
        "description": "Hired as GIS expert to produce Net Plantable Area (NPA) Maps for several undeveloped land properties in Australia.",
        "projectValue": "",
        "projectScale": "",
        "status": "Project-based",
        "sector1": "Spatial Analysis",
        "sector2": "Real Estate",
        "photo1": "https://assets-global.website-files.com/6213793139128577f6ba751b/62ea6ceb0175673ed95b4b45_Layout1-p-800.jpg",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 40.0023425861252,
        "lng": -83.0049312297663,
        "projectName": "GIS Specialist",
        "country": "USA",
        "location": "Ohio ",
        "startDate": "Feb 2022",
        "completionDate": "Feb 2022",
        "partner": "Remote",
        "client": "Individual client",
        "clientType": "Private",
        "description": "Hired as GIS expert to overlay old maps in certain part of Ohio and help figure out what changed through the years.",
        "projectValue": "",
        "projectScale": "",
        "status": "Project-based",
        "sector1": "GIS Data Extraction",
        "sector2": "Cartography",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 24.2455416806188,
        "lng": 44.2660540632862,
        "projectName": "GIS Specialist",
        "country": "Saudi Arabia",
        "location": "",
        "startDate": "Aug 2022",
        "completionDate": "Nov 2022",
        "partner": "Remote",
        "client": "Individual client",
        "clientType": "Private",
        "description": "Contracted as a GIS expert to perform least cost path analysis to delinieate all possible ancient camel (yes, camels!) trade routes used in the middle east back in the day.",
        "projectValue": "",
        "projectScale": "",
        "status": "Project-based",
        "sector1": "Spatial Analysis",
        "sector2": "Archeaology",
        "photo1": "https://images.pexels.com/photos/3121285/pexels-photo-3121285.jpeg",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 10.7810454269881,
        "lng": 106.698425766226,
        "projectName": "Senior GIS Associate",
        "country": "Vietnam",
        "location": "Ho Chi Minh City ",
        "startDate": "Aug 2022",
        "completionDate": "Till date",
        "partner": "On-site",
        "client": "enCity",
        "clientType": "Private",
        "description": "Senior GIS associate supporting varying projects. Geospatial data acqusition, analysis and visualization. Also involved in internal and client facing web map app development.",
        "projectValue": "",
        "projectScale": "",
        "status": "Full-time",
        "sector1": "GIS Web App Development",
        "sector2": "Spatial Data Extraction",
        "photo1": "https://raw.githubusercontent.com/cmlosariaGIS/enCityProjects/main/Projects/01_Thu%20Duc%20City%20GIS%20Planning%20Platform/Images/Picture1.jpg",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 10.8203192,
        "lng": 106.7074485,
        "projectName": "Thu Duc City web GIS Platform for planning and stakeholder engagement",
        "country": "Vietnam",
        "location": "Thu Duc City ",
        "startDate": "Nov 2022",
        "completionDate": "Nov 2022",
        "partner": "On-site",
        "client": "Thu Duc City",
        "clientType": "Government",
        "description": "Technical Lead (GIS). In close coordination with Thu Duc City’s Urban Management Division, we developed an interactive online dashboard to enable the city planners in better decision-making through side-by-side comparison of various spatial information such as the existing conditions, the existing land use plan and the revised land use plan.",
        "projectValue": "",
        "projectScale": "",
        "status": "Project-based",
        "sector1": "GIS Web App Development",
        "sector2": "Urban and Regional Planning",
        "photo1": "https://raw.githubusercontent.com/cmlosariaGIS/enCityProjects/main/Projects/01_Thu%20Duc%20City%20GIS%20Planning%20Platform/Images/Picture1.jpg",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 21.0055645786822,
        "lng": 105.803904253652,
        "projectName": "GIS Engineer",
        "country": "Vietnam",
        "location": "Hanoi",
        "startDate": "Jan 2023",
        "completionDate": "Till date",
        "partner": "On-site",
        "client": "enCity / enSigthful / enFarm Agritech",
        "clientType": "Private",
        "description": "Senior GIS associate supporting varying projects. My main roles are geospatial data acqusition, analysis and visualization. Also do web map app development for our agritech product.",
        "projectValue": "",
        "projectScale": "",
        "status": "Full-time",
        "sector1": "GIS Web App Development",
        "sector2": "Agriculture",
        "photo1": "https://i.ibb.co/jfPcNSc/Capture2.jpg",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 14.5816923,
        "lng": 121.0599841,
        "projectName": "USAID - PIMMELA",
        "country": "Philippines, Mogolia, Pacific Islands",
        "location": "",
        "startDate": "July 2024",
        "completionDate": "Till date",
        "partner": "Remote",
        "client": "Management Systems International (MSI)/Tetra Tech",
        "clientType": "Private",
        "description": "Lead technical expert to (i) prepare and convert existing tabulated datasets into GIS\nvisualization maps. (ii) Developing Tableau data visualization dashboards for interactive\nway of visualizing and drilling down of data. (iii) Provide technical assistance and\nrecommendations for digital solutions.",
        "projectValue": "",
        "projectScale": "",
        "status": "Project-based",
        "sector1": "GIS Web App Development",
        "sector2": "Health, Development",
        "photo1": "https://i.ibb.co/TBz2cyc0/PIMMELA.png",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 39.41922,
        "lng": -111.950684,
        "projectName": "Web Map Developer",
        "country": "USA",
        "location": "Utah",
        "startDate": "Aug 2024",
        "completionDate": "Till date",
        "partner": "Remote",
        "client": "Federalism Index Project",
        "clientType": "Private",
        "description": "Role as Web Map Developer to create engaging web maps to showcase various information on US Senate and Congress.",
        "projectValue": "",
        "projectScale": "",
        "status": "Project-based",
        "sector1": "GIS Web App Development",
        "sector2": "Politics",
        "photo1": "https://cdn.prod.website-files.com/6213793139128577f6ba751b/670aa3843d20ce5d4f0c86bd_Federalism%20Index%20Project.png",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 62,
        "lng": 15,
        "projectName": "GIS Specialist",
        "country": "Sweden",
        "location": "",
        "startDate": "Nov 2022",
        "completionDate": "Till date",
        "partner": "Remote",
        "client": "OurHistory ",
        "clientType": "Private",
        "description": "Process old maps of Sweden and its territories and created GIS data for web application visualization",
        "projectValue": "",
        "projectScale": "",
        "status": "Project-based",
        "sector1": "GIS Web App Development",
        "sector2": "History",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    },
    {
        "lat": 31,
        "lng": 99,
        "projectName": "GIS Specialist",
        "country": "USA",
        "location": "Texas",
        "startDate": "July 2024",
        "completionDate": "August 2024",
        "partner": "Remote",
        "client": "Private",
        "clientType": "Private",
        "description": "Managed ArcGIS Online contents. Developed scripts to automate site suitability analysis for data center construction. Developed dashbaord using Esri ArcGIS Experience Builder",
        "projectValue": "",
        "projectScale": "",
        "status": "Project-based",
        "sector1": "GIS Web App Development",
        "sector2": "",
        "photo1": "",
        "photo2": "",
        "attachment": ""
    }
];

// Add more Project data rows as needed
